### ISSUE TITLE
border-layout is not a real CSS attribute

### ISSUE THREAD

**Issue by btopro** [McGarvelcuddy/monopoly-card#1]
https://github.com/McGarvelcuddy/monopoly-card/blob/26a78f3f4d51f5fdd3cac6f330c6976222d56a03/src/MonopolyCard.js#L17

**Comment by McGarvelcuddy** [comment]
Idk where I thought I saw that, or thought it did anything, but it will be removed

**Comment by McGarvelcuddy** [comment]
Removed in most recent push
