### ISSUE TITLE
itemDescription not itemdescription

### ISSUE THREAD

**Issue by btopro** [McGarvelcuddy/monopoly-card#2]
https://github.com/McGarvelcuddy/monopoly-card/blob/26a78f3f4d51f5fdd3cac6f330c6976222d56a03/src/MonopolyCard.js#L53

review LitElement docs around the use of `attribute` and camelCase so that users get an experience like `item-description` or just `description` instead of a run on word

**Comment by McGarvelcuddy** [comment]
Renaming it to camelCase, and doing  `itemDescription: { attribute: "item-description" },`  as well

**Comment by btopro** [comment]
make sure type: String is in there as well

**Comment by McGarvelcuddy** [comment]
Pushed this suggestion
